[window]

opacity = 0.75

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" #"Light" # "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]


[colors.primary]
background= '#171817'
foreground= '#ad9375'

  # Normal colors
[colors.normal]
black=   '#191f1e'
red= '#b85555'
green=   '#959e44'
yellow=  '#e09243'
blue=    '#5f819d'
magenta= '#a174b0'
cyan=    '#4d9289'
white=   '#707880'

  # Bright colors
[colors.bright]
black=   '#191f1e'
red=     '#cc6666'
green=   '#b5bd68'
yellow=  '#e5bf64'
blue=    '#81a2be'
magenta= '#b294bb'
cyan=    '#8abeb7'
white=   '#c5c8c6'
